from driver.multi_air.multi_air_driver import MultiAirModule as SensorHubModule
from driver.multi_air.multi_air_driver import MultiAirModuleSensors as SENSORS
from driver.multi_air.multi_air_driver import MultiAirModuleSensorsColumns as SENSORS_COLS
